### ISSUE TITLE
Examples and Website Documentation Error

### ISSUE THREAD

**Issue by Nessworthy** [adriancooney/aristochart#3]
Hi,

Looking through the website and examples, I keep encountering this JS Error:
`TypeError: code.innerText is undefined` (Examples.js:10)

For me, this breaks all of the JS on the website.

**Comment by adriancooney** [comment]
Ah crap! I thought I had gone past this. For the longest time I thought the `innerText` property was the standard for setting the text content of an element but Firefox doesn't support it! `textContent` is the actual property that needs to be fixed. I get on that, thanks.

**Comment by Nessworthy** [comment]
♥

Hurray for standardisation of browsers!

**Comment by adriancooney** [comment]
Thanks!
